GET http://localhost:3003/api/users


### SELECT ONLY ONE BY ID
GET http://localhost:3003/api/blogs/623ffde6e3600866551b2178


### BAD ID
GET http://localhost:3003/api/blogs/623cdc89ab7669c2d8230290


### WHEN YOU PUT ANYTHING
GET http://localhost:3003/api/blogs/Helloword