POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Joao",
    "title": "Barcelona",
    "url": "whatevel",
    "likes": 80
}


### Create blog without likes
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Jair",
    "title": "Madrid",
    "url": "whatever"
}


### Create blog without author
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Madrid",
    "url": "whatever"
}