POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhIiwiaWQiOiI2MjNmZmRlNmUzNjAwODY2NTUxYjIxNzgiLCJpYXQiOjE2NDg3Njg2NDMsImV4cCI6MTY0ODc3MjI0M30.rDnwPIuz_bHPYxoFAUaMl76UPzsFZGtOoiDF9rvccfs

{
    "author": "Lets add",
    "title": "Final",
    "url": "Anderson",
    "likes": 139
}


### Create blog without likes
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhIiwiaWQiOiI2MjNmZmRlNmUzNjAwODY2NTUxYjIxNzgiLCJpYXQiOjE2NDg2ODc1MzAsImV4cCI6MTY0ODY5MTEzMH0.P2OO1SOtfxtxxvYQS51WcKB3gWmDr4nQQwgkKQCE-T0

{
    "author": "Without",
    "title": "Madrid",
    "url": "rock"
}


### Create blog without url
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhIiwiaWQiOiI2MjNmZmRlNmUzNjAwODY2NTUxYjIxNzgiLCJpYXQiOjE2NDg2ODc1MzAsImV4cCI6MTY0ODY5MTEzMH0.P2OO1SOtfxtxxvYQS51WcKB3gWmDr4nQQwgkKQCE-T0

{
    "author": "Without",
    "title": "Madrid"
}


### wrong token auth
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RhIiwiaWQiOiI2MjNmZmRlNmUzNjAwODY2NTUxYjIxNzgiLCJpYXQiOjE2NDg2ODc1MzAsImV4cCI6MTY0ODY5MTEzMH0.P2OO1SOtfxtxxvYQS51WcKB3gWmDr4nQQwgkKQCE409

{
    "author": "Liviano",
    "title": "Comes",
    "url": "Anders",
    "likes": 79
}


### secure wrong token auth
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer hello_world

{
    "author": "Liviano",
    "title": "Comes",
    "url": "Anders",
    "likes": 79
}


### without bearer
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: hello_world

{
    "author": "Liviano",
    "title": "Comes",
    "url": "Anders",
    "likes": 79
}